// Harness: extract the pure-JS spline math from lgs_companion.qml
// verbatim and check its structural guarantees. With an optional second
// argument, also run numeric parity fixtures generated by
// tests/test_qfield_spline_js.py from the desktop Hermite algorithm.
// Run: node spline_harness.js <path-to-qml> [fixture.json]
'use strict'
const fs = require('fs')

const qmlPath = process.argv[2]
const fixturePath = process.argv[3]
const qml = fs.readFileSync(qmlPath, 'utf8')

function extractFunction(name) {
  const start = qml.indexOf('function ' + name + '(')
  if (start === -1) throw new Error('function not found: ' + name)
  let depth = 0, i = qml.indexOf('{', start)
  const bodyStart = i
  for (; i < qml.length; i++) {
    if (qml[i] === '{') depth++
    else if (qml[i] === '}') { depth--; if (depth === 0) break }
  }
  return 'function ' + name + qml.slice(qml.indexOf('(', start), bodyStart) +
         qml.slice(bodyStart, i + 1)
}

const code = ['splinePointScalar', 'splinePointsAdd', 'splineTangent',
  'splinePerpDist', 'splineSimplifyIndices', 'splineSimplify',
  'splineRefineAngles', 'splineDecimate', 'splineSamePoint',
  'splineQuantizeUnits', 'splineEffectiveTolerance', 'splineSampleCount',
  'splineDensityKey',
  'splineCacheEntries', 'splineCacheLookup', 'splineHermiteOpen',
  'splineHermiteClosed', 'splineBuildSequence', 'splineConfirmSequence',
  'splineCommonPrefixLength', 'splineRingIdleSequence', 'splineSeqToWkt']
  .map(extractFunction).join('\n');
// Indirect eval: runs non-strict in global scope so the extracted
// function declarations become globals.
(0, eval)(code)
const simplify = globalThis.splineSimplify
const hermiteOpen = globalThis.splineHermiteOpen
const hermiteClosed = globalThis.splineHermiteClosed
const buildSequence = globalThis.splineBuildSequence
const confirmSequence = globalThis.splineConfirmSequence
const commonPrefix = globalThis.splineCommonPrefixLength
const decimate = globalThis.splineDecimate
const ringIdle = globalThis.splineRingIdleSequence
const seqToWkt = globalThis.splineSeqToWkt
const quantize = globalThis.splineQuantizeUnits
const effTol = globalThis.splineEffectiveTolerance
const sampleCount = globalThis.splineSampleCount
const densityKey = globalThis.splineDensityKey
const refineAngles = globalThis.splineRefineAngles
const simplifyIndices = globalThis.splineSimplifyIndices

// The density constants are QML properties, not functions, so pin them by
// reading the source rather than restating them here — a retune of
// splineTolPoints must not silently leave these checks testing the old
// number.
function qmlReal(name) {
  const m = qml.match(new RegExp('readonly property (?:real|int) ' + name +
                                 ': ([0-9.]+)'))
  if (!m) throw new Error('constant not found: ' + name)
  return Number(m[1])
}
const TOL_POINTS = qmlReal('splineTolPoints')
const SPACING_POINTS = qmlReal('splineSampleSpacingPoints')
const MIN_SAMPLES = qmlReal('splineMinSamples')
const KINK_RATIO = qmlReal('splineMaxKinkRatio')
function dens(unitsPerPoint) {
  return { unitsPerPoint: unitsPerPoint, tolPoints: TOL_POINTS,
           spacingPoints: SPACING_POINTS, minSamples: MIN_SAMPLES,
           maxKinkRatio: KINK_RATIO }
}
// The kink at a vertex: how far the line visibly corners there. This is
// what the eye reads as faceting, and what Douglas-Peucker on its own says
// nothing about. Returned in POINTS on the map, so it is comparable across
// scales; multiply by 0.3528 for millimetres.
function maxKinkPoints(seq, unitsPerPoint) {
  let worst = 0
  for (let i = 1; i < seq.length - 1; i++) {
    const ax = seq[i].x - seq[i - 1].x, ay = seq[i].y - seq[i - 1].y
    const bx = seq[i + 1].x - seq[i].x, by = seq[i + 1].y - seq[i].y
    const la = Math.sqrt(ax * ax + ay * ay), lb = Math.sqrt(bx * bx + by * by)
    if (!(la > 0) || !(lb > 0)) continue
    let c = (ax * bx + ay * by) / (la * lb)
    c = c > 1 ? 1 : (c < -1 ? -1 : c)
    const t = Math.acos(c)
    worst = Math.max(worst, (la < lb ? la : lb) / 2 * Math.tan(t / 2))
  }
  return worst / unitsPerPoint
}
function effTolFor(u) { return Math.max(0.1, u * TOL_POINTS) }

let failures = 0
function check(label, ok, detail) {
  if (ok) { console.log('PASS ' + label); return }
  failures++
  console.log('FAIL ' + label)
  if (detail) console.log('  ' + detail)
}

function pt(x, y, z) { return { x: x, y: y, z: z } }
function samePt(a, b) { return a.x === b.x && a.y === b.y }
function containsInOrder(seq, controls) {
  let at = 0
  for (const c of controls) {
    while (at < seq.length && !samePt(seq[at], c)) at++
    if (at === seq.length) return false
    at++
  }
  return true
}

// --- passthrough below 3 points -----------------------------------
const two = [pt(0, 0), pt(1, 1)]
check('open passthrough < 3 points',
  JSON.stringify(hermiteOpen(two, 0.5, 0, 8)) === JSON.stringify(two))
check('closed passthrough < 3 points',
  JSON.stringify(hermiteClosed(two, 0.5, 0, 8).points) === JSON.stringify(two))
check('buildSequence passthrough < 3 distinct points',
  JSON.stringify(buildSequence([pt(0, 0), pt(1, 1), pt(1, 1)], false, 0.5, 0, 8))
    === JSON.stringify([pt(0, 0), pt(1, 1)]))

// --- open curve: exact endpoints, controls preserved in order -------
const wiggle = [pt(0, 0, 100), pt(10, 5, 110), pt(20, -5, 120), pt(30, 0, 130)]
const open8 = hermiteOpen(wiggle, 0.5, 0, 8)
check('open endpoints exact',
  samePt(open8[0], wiggle[0]) && samePt(open8[open8.length - 1], wiggle[3]))
check('open controls preserved in order', containsInOrder(open8, wiggle))
// tolerance=0 keeps every sample: n controls + (n-1) * (maxSegments-1)
check('open exact count at tolerance 0 (maxSegments 8)',
  open8.length === 4 + 3 * 7, 'got ' + open8.length)

// --- collinear input prunes back to the control points --------------
const line = [pt(0, 0), pt(1, 0), pt(2, 0), pt(3, 0)]
const pruned = hermiteOpen(line, 0.5, 0.5, 8)
check('collinear prunes to controls',
  pruned.length === 4 && line.every((c, i) => samePt(pruned[i], c)),
  'got ' + JSON.stringify(pruned))

// --- z handling -----------------------------------------------------
const zLinear = open8.every((p, i) => {
  if (i === 0) return p.z === 100
  return p.z >= open8[i - 1].z - 1e-9
})
check('z present, exact at controls, non-decreasing', zLinear &&
  open8[open8.length - 1].z === 130)
const open2d = hermiteOpen([pt(0, 0), pt(10, 5), pt(20, -5)], 0.5, 0, 8)
check('2D input yields NaN sample z, xy stays finite',
  open2d.every(p => isFinite(p.x) && isFinite(p.y)) &&
  open2d.some(p => Number.isNaN(p.z)))

// --- closed ring ----------------------------------------------------
const square = [pt(0, 0), pt(10, 0), pt(10, 10), pt(0, 10)]
const ring = hermiteClosed(square, 0.5, 0, 8)
check('closed: all controls present', containsInOrder(ring.points, square))
check('closed: no closing duplicate',
  !samePt(ring.points[0], ring.points[ring.points.length - 1]))
check('closed: lastControlIndex points at last control',
  samePt(ring.points[ring.lastControlIndex], square[3]))
check('closed: wrap samples follow the last control',
  ring.points.length > ring.lastControlIndex + 1)
// n segments * (maxSegments-1) samples + n controls
check('closed exact count at tolerance 0 (maxSegments 8)',
  ring.points.length === 4 + 4 * 7, 'got ' + ring.points.length)

// --- buildSequence rotation (closed) --------------------------------
const seq = buildSequence(square, true, 0.5, 0, 8)
check('rotation: crosshair control is last', samePt(seq[seq.length - 1], square[3]))
check('rotation: length preserved', seq.length === ring.points.length)
check('rotation: first element is a wrap sample',
  samePt(seq[0], ring.points[ring.lastControlIndex + 1]))
check('rotation: all controls present', containsInOrder(
  seq.slice(seq.indexOf(seq.find(p => samePt(p, square[0])))), square))

// --- buildSequence open ends at crosshair ---------------------------
const seqOpen = buildSequence(wiggle, false, 0.5, 0, 8)
check('open sequence ends at crosshair',
  samePt(seqOpen[seqOpen.length - 1], wiggle[3]))

// --- confirmSequence: committed controls only, no crosshair ---------
check('confirm open: null below 2 distinct controls',
  confirmSequence([pt(0, 0), pt(0, 0)], false, 0.5, 0, 8) === null &&
  confirmSequence([], false, 0.5, 0, 8) === null)
check('confirm closed: null below 3 distinct controls',
  confirmSequence([pt(0, 0), pt(10, 0)], true, 0.5, 0, 8) === null)
check('confirm open: 2 controls pass through as the plain segment',
  JSON.stringify(confirmSequence(two, false, 0.5, 0, 8)) ===
  JSON.stringify(two))
const confOpen = confirmSequence(wiggle, false, 0.5, 0, 8)
check('confirm open: endpoints are the first/last CONTROLS',
  samePt(confOpen[0], wiggle[0]) &&
  samePt(confOpen[confOpen.length - 1], wiggle[3]))
check('confirm open: all controls present in order',
  containsInOrder(confOpen, wiggle))
check('confirm open matches the committed-only curve',
  JSON.stringify(confOpen) === JSON.stringify(hermiteOpen(wiggle, 0.5, 0, 8)))
const confRing = confirmSequence(square, true, 0.5, 0, 8)
check('confirm closed: all controls present, no closing duplicate',
  containsInOrder(confRing, square) &&
  !samePt(confRing[0], confRing[confRing.length - 1]))
check('confirm closed matches the committed-only ring',
  JSON.stringify(confRing) ===
  JSON.stringify(hermiteClosed(square, 0.5, 0, 8).points))
// The property the confirm fixup exists for: the sequence the crosshair
// WOULD have contributed (buildSequence with the crosshair appended)
// differs past the last control — confirm uses the controls-only curve.
const jiggled = pt(99, 99)
const withCross = buildSequence(wiggle.concat([jiggled]), false, 0.5, 0, 8)
check('confirm: crosshair never contributes',
  !confOpen.some(p => samePt(p, jiggled)) &&
  samePt(withCross[withCross.length - 1], jiggled) &&
  !samePt(confOpen[confOpen.length - 1], jiggled))

// --- duplicates never explode ---------------------------------------
const dup = buildSequence(
  [pt(0, 0), pt(0, 0), pt(10, 5), pt(10, 5), pt(20, 0)], false, 0.5, 0, 8)
check('duplicate controls produce finite xy',
  dup.every(p => isFinite(p.x) && isFinite(p.y)))

// --- decimate (freehand node thinning) -------------------------------
const dense = []
for (let i = 0; i <= 20; i++) dense.push(pt(i, 0, i))
check('decimate: minDist 0 is identity',
  JSON.stringify(decimate(dense, 0)) === JSON.stringify(dense))
const thinned = decimate(dense, 5)
check('decimate: keeps first and last',
  samePt(thinned[0], dense[0]) &&
  samePt(thinned[thinned.length - 1], dense[20]))
check('decimate: dense run collapses to every 5th point',
  thinned.length === 5 &&
  thinned.every((p, i) => i === thinned.length - 1 || p.x === i * 5),
  'got ' + JSON.stringify(thinned))
check('decimate: kept points carry their z',
  thinned.every(p => p.z === p.x))
const sparse = [pt(0, 0), pt(10, 0), pt(20, 0)]
check('decimate: already-sparse input passes through',
  JSON.stringify(decimate(sparse, 5)) === JSON.stringify(sparse))
check('decimate: two points always survive',
  decimate([pt(0, 0), pt(1, 0)], 100).length === 2)

// --- simplify basics ------------------------------------------------
const spike = [pt(0, 0), pt(1, 0.001), pt(2, 5), pt(3, 0.001), pt(4, 0)]
check('simplify: tolerance 0 is identity',
  JSON.stringify(simplify(spike, 0)) === JSON.stringify(spike))
const simp = simplify(spike, 0.01)
check('simplify: keeps endpoints and the spike',
  samePt(simp[0], spike[0]) && samePt(simp[simp.length - 1], spike[4]) &&
  simp.some(p => samePt(p, spike[2])))
const nearFlat = [pt(0, 0), pt(1, 0.001), pt(2, 0.002), pt(4, 0)]
check('simplify: drops sub-tolerance points',
  simplify(nearFlat, 0.01).length === 2,
  'got ' + JSON.stringify(simplify(nearFlat, 0.01)))

// --- common prefix (incremental rebuild diff) -----------------------
const seqA = [pt(0, 0, 1), pt(1, 1, 2), pt(2, 2, 3)]
check('prefix: identical arrays -> full length',
  commonPrefix(seqA, seqA.map(p => pt(p.x, p.y, p.z))) === 3)
check('prefix: divergence mid-array',
  commonPrefix(seqA, [pt(0, 0, 1), pt(1, 1.5, 2), pt(2, 2, 3)]) === 1)
check('prefix: shorter second array caps the walk',
  commonPrefix(seqA, [pt(0, 0, 1)]) === 1)
check('prefix: empty arrays', commonPrefix([], seqA) === 0)
check('prefix: z mismatch counts as divergence',
  commonPrefix(seqA, [pt(0, 0, 1), pt(1, 1, 9), pt(2, 2, 3)]) === 1)
check('prefix: NaN z equals NaN z',
  commonPrefix([pt(0, 0, NaN), pt(1, 1, NaN)],
               [pt(0, 0, NaN), pt(1, 1, NaN)]) === 2)
check('prefix: undefined z equals NaN z',
  commonPrefix([pt(0, 0), pt(1, 1)],
               [pt(0, 0, NaN), pt(1, 1, NaN)]) === 2)
// The property the incremental rebuild relies on: moving only the
// crosshair leaves a long stable prefix on an open curve.
const cross1 = hermiteOpen(wiggle.slice(0, 3).concat([pt(31, 1, 130)]), 0.5, 0, 8)
const cross2 = hermiteOpen(wiggle.slice(0, 3).concat([pt(33, -2, 130)]), 0.5, 0, 8)
check('prefix: crosshair move keeps stable prefix on open curve',
  commonPrefix(cross1, cross2) >= 1 + 7 + 1,  // first segment + controls
  'got ' + commonPrefix(cross1, cross2))

// --- segment cache: cached output is bit-identical -------------------
// The confirm-path cache must never change the produced curve — only
// skip recomputing segments whose dependencies are unchanged.
function sameJson(a, b) { return JSON.stringify(a) === JSON.stringify(b) }
const cacheO = {}
const grow = [pt(0, 0, 100), pt(10, 5, 110), pt(20, -5, 120)]
let growOk = true
for (const next of [pt(30, 0, 130), pt(40, 8, 140), pt(45, 20, 150)]) {
  grow.push(next)
  if (!sameJson(hermiteOpen(grow, 0.5, 0.1, 200, cacheO),
                hermiteOpen(grow, 0.5, 0.1, 200)))
    growOk = false
}
check('cache open: incremental appends stay bit-identical', growOk)
grow.pop()
check('cache open: pop stays bit-identical',
  sameJson(hermiteOpen(grow, 0.5, 0.1, 200, cacheO),
           hermiteOpen(grow, 0.5, 0.1, 200)))
const cacheC = {}
const ringGrow = [pt(0, 0), pt(10, 0), pt(10, 10)]
let ringOk = true
for (const next of [pt(5, 15), pt(0, 10)]) {
  ringGrow.push(next)
  const cached = hermiteClosed(ringGrow, 0.5, 0.1, 200, cacheC)
  const plain = hermiteClosed(ringGrow, 0.5, 0.1, 200)
  if (!sameJson(cached.points, plain.points) ||
      cached.lastControlIndex !== plain.lastControlIndex)
    ringOk = false
}
check('cache closed: incremental appends stay bit-identical', ringOk)
check('cache: buildSequence with cache matches without (closed rotation)',
  sameJson(buildSequence(ringGrow, true, 0.5, 0.1, 200, cacheC),
           buildSequence(ringGrow, true, 0.5, 0.1, 200)))
check('cache: confirmSequence with cache matches without',
  sameJson(confirmSequence(wiggle, false, 0.5, 0, 8, {}),
           confirmSequence(wiggle, false, 0.5, 0, 8)))
// The property the cache exists for: a repeated call replays the exact
// stored blocks (object identity, not just equal values)...
const cacheHit = {}
const hit1 = hermiteOpen(wiggle, 0.5, 0, 8, cacheHit)
const hit2 = hermiteOpen(wiggle, 0.5, 0, 8, cacheHit)
check('cache: repeated call reuses stored blocks (object identity)',
  hit2.length === hit1.length && hit2[1] === hit1[1])
// ...and a moved last point (the crosshair) leaves the early segments'
// blocks untouched while the tail recomputes.
const cacheTail = {}
const tail1 = hermiteOpen(wiggle.concat([pt(40, 0, 140)]), 0.5, 0, 8, cacheTail)
const tail2 = hermiteOpen(wiggle.concat([pt(41, 3, 140)]), 0.5, 0, 8, cacheTail)
check('cache: crosshair move keeps early blocks (identity), tail differs',
  tail2[1] === tail1[1] &&
  !samePt(tail2[tail2.length - 2], tail1[tail1.length - 2]))
// Open and closed entries never cross-contaminate, even for the same
// control points.
const cacheKind = {}
hermiteClosed(square, 0.5, 0, 8, cacheKind)
check('cache: open/closed kinds are separate',
  sameJson(hermiteOpen(square, 0.5, 0, 8, cacheKind),
           hermiteOpen(square, 0.5, 0, 8)))
// A parameter change invalidates everything.
const cacheParams = {}
hermiteOpen(wiggle, 0.5, 0, 8, cacheParams)
check('cache: params change invalidates and stays correct',
  sameJson(hermiteOpen(wiggle, 0.8, 0, 8, cacheParams),
           hermiteOpen(wiggle, 0.8, 0, 8)) &&
  cacheParams.p[0] === 0.8)

// --- v26 ring-aligned idle sequence ---------------------------------
// The polygon-confirm fix: the idle upgrade writes the CONFIRM ring
// plus the crosshair as floating tail, so the confirm sequence is a
// full prefix of what the model already holds and the confirm write
// collapses to a tail rewrite.
const cacheRing = {}
const crossPt = pt(3, -4)
const idleSeq = ringIdle(square, crossPt, 0.5, 0, 8, cacheRing)
const confSeq = confirmSequence(square, true, 0.5, 0, 8, cacheRing)
check('ring idle: confirm ring is a full prefix of the idle sequence',
  commonPrefix(idleSeq, confSeq) === confSeq.length,
  'prefix ' + commonPrefix(idleSeq, confSeq) + ' of ' + confSeq.length)
check('ring idle: exactly one extra vertex, the crosshair',
  idleSeq.length === confSeq.length + 1 &&
  samePt(idleSeq[idleSeq.length - 1], crossPt))
check('ring idle: cache does not change the sequence',
  sameJson(ringIdle(square, crossPt, 0.5, 0, 8), idleSeq))
check('ring idle: null below 3 distinct controls',
  ringIdle([pt(0, 0), pt(10, 0), pt(10, 0)], crossPt, 0.5, 0, 8) === null)

// Write-cost simulation pinned to splineWriteSequence's cap arithmetic
// in lgs_companion.qml: after the idle write the model holds idleSeq
// (vertexCount = idleSeq.length, last vertex floating). The confirm
// write of confSeq must take the incremental branch with exactly
// 1 removeVertex + 1 addVertexFromPoint (+ the trailing removeVertex).
{
  const lastSeq = idleSeq
  const modelCount = idleSeq.length
  const seq = confSeq
  let prefix = commonPrefix(lastSeq, seq)
  prefix = Math.min(prefix, lastSeq.length - 1, modelCount - 1,
                    seq.length - 1)
  const pops = modelCount - (prefix + 1)
  const incrementalCost = pops + (seq.length - prefix) + 1
  const fullCost = seq.length + 2
  check('ring idle: confirm takes the incremental branch',
    prefix > 0 && incrementalCost < fullCost && pops >= 0,
    'prefix ' + prefix + ' pops ' + pops)
  check('ring idle: confirm write is 1 pop + 1 add',
    pops === 1 && seq.length - prefix === 1,
    'pops ' + pops + ' adds ' + (seq.length - prefix))
}

// --- v26 WKT builder (bulk confirm write) ---------------------------
check('wkt: 2D linestring',
  seqToWkt([pt(0, 0), pt(1.5, 2)], false) === 'LINESTRING (0 0, 1.5 2)')
check('wkt: z emitted only when every vertex has finite z',
  seqToWkt([pt(0, 0, 5), pt(1, 1, 6)], false) ===
    'LINESTRING Z (0 0 5, 1 1 6)' &&
  seqToWkt([pt(0, 0, 5), pt(1, 1, NaN)], false) ===
    'LINESTRING (0 0, 1 1)')
check('wkt: polygon appends the closing duplicate',
  seqToWkt([pt(0, 0), pt(10, 0), pt(5, 8)], true) ===
  'POLYGON ((0 0, 10 0, 5 8, 0 0))')
check('wkt: already-closed polygon input is not double-closed',
  seqToWkt([pt(0, 0), pt(10, 0), pt(5, 8), pt(0, 0)], true) ===
  'POLYGON ((0 0, 10 0, 5 8, 0 0))')
check('wkt: empty sequence is null', seqToWkt([], false) === null)

// --- v27 scale-adaptive density -------------------------------------
// The legacy path must stay bit-identical: an absent density and an
// explicit null are the same thing, and both are what the numeric parity
// fixtures below exercise against the desktop algorithm.
check('density: absent and null density agree',
  sameJson(hermiteOpen(wiggle, 0.5, 0, 8),
           hermiteOpen(wiggle, 0.5, 0, 8, null, null)) &&
  sameJson(hermiteClosed(square, 0.5, 0, 8).points,
           hermiteClosed(square, 0.5, 0, 8, null, null).points))
check('density: no density leaves the sample count at maxSegments',
  sampleCount(pt(0, 0), pt(100, 0), pt(50, 0), pt(50, 0), 200, null) === 200)

// Octave quantization. Exact powers of two are fixed points, and a zoom
// that does not cross an octave must not move the value — that is what
// keeps the segment cache alive across ordinary panning and pinching.
check('quantize: exact powers of two are fixed points',
  quantize(0.25) === 0.25 && quantize(1) === 1 && quantize(4) === 4 &&
  quantize(1024) === 1024)
check('quantize: rounds to the nearer octave',
  quantize(1.3) === 1 && quantize(1.5) === 2 && quantize(0.6) === 0.5 &&
  quantize(0.8) === 1)
// Boundaries exist by construction, so the honest invariant is not "a
// small zoom never moves it" but "it is monotonic and changes rarely":
// across a full 2x zoom sweep it takes at most two values, which is what
// bounds how often the segment cache is thrown away.
{
  const sweep = []
  for (let i = 0; i <= 40; i++)
    sweep.push(quantize(0.5 * Math.pow(2, i / 40)))
  const distinct = sweep.filter((v, i) => i === 0 || v !== sweep[i - 1])
  let monotonic = true
  for (let i = 1; i < sweep.length; i++)
    if (sweep[i] < sweep[i - 1]) monotonic = false
  check('quantize: monotonic, and at most two values across a 2x sweep',
    monotonic && distinct.length <= 2, distinct.join(' -> '))
}
check('quantize: rejects unusable readings',
  quantize(0) === 0 && quantize(-1) === 0 && quantize(NaN) === 0 &&
  quantize(Infinity) === 0 && quantize(1e-30) === 0 && quantize(1e30) === 0)

// Tolerance is a deviation at the mapping scale, with the baked desktop
// value surviving as the fallback.
check('tolerance: derived from units per point',
  effTol(0.1, dens(2)) === 2 * TOL_POINTS)
check('tolerance: falls back to the baked value without density',
  effTol(0.1, null) === 0.1 &&
  effTol(0.1, dens(0)) === 0.1)
// Zoomed right in the derived value goes under the baked tolerance; it
// must clamp, or close-in drawing would come out SLOWER than before.
check('tolerance: never finer than the baked tolerance',
  effTol(0.1, dens(0.01)) === 0.1 &&
  effTol(0.1, dens(0.0001)) === 0.1)

// Sample count follows the segment's on-screen length, between the floor
// and the caller's cap.
check('sample count: floors at splineMinSamples for a tiny segment',
  sampleCount(pt(0, 0), pt(0.001, 0), pt(0, 0), pt(0, 0), 200,
              dens(1)) === MIN_SAMPLES)
check('sample count: caps at maxSegments for a huge segment',
  sampleCount(pt(0, 0), pt(1e6, 0), pt(0, 0), pt(0, 0), 200,
              dens(1)) === 200)
check('sample count: honours a live-preview cap below the floor',
  sampleCount(pt(0, 0), pt(0.001, 0), pt(0, 0), pt(0, 0), 2,
              dens(1)) === 2)
check('sample count: grows as the segment gets longer on screen',
  sampleCount(pt(0, 0), pt(40, 0), pt(0, 0), pt(0, 0), 200, dens(1)) >
  sampleCount(pt(0, 0), pt(10, 0), pt(0, 0), pt(0, 0), 200, dens(1)))
check('sample count: bounds the arc, not just the chord',
  sampleCount(pt(0, 0), pt(10, 0), pt(0, 60), pt(0, -60), 200, dens(1)) >
  sampleCount(pt(0, 0), pt(10, 0), pt(0, 0), pt(0, 0), 200, dens(1)))

// The point of the whole change: coarser scale, fewer saved vertices —
// monotonically, and with a real cut at ordinary mapping scales. The
// control points always survive, so they are the floor.
{
  const trace = []
  for (let i = 0; i < 8; i++)
    trace.push(pt(i * 12, (i % 2 === 0 ? 6 : -6) + i))
  const counts = [0.125, 0.5, 2, 8].map(
    u => hermiteOpen(trace, 0.5, 0.1, 200, null, dens(u)).length)
  let monotonic = true
  for (let i = 1; i < counts.length; i++)
    if (counts[i] > counts[i - 1]) monotonic = false
  // Monotonic from the mapping-scale band outward. Finer than that the
  // prune tolerance is pinned at the baked floor while sampling keeps
  // changing, so the count is not required to fall in lockstep.
  check('density: node count is non-increasing as the scale coarsens',
    monotonic, counts.join(' -> '))
  check('density: a coarse scale cuts the node count hard',
    counts[counts.length - 1] * 4 < counts[0],
    counts.join(' -> '))
  check('density: control points survive at every scale',
    [0.001, 0.03125, 0.125, 0.5, 2, 8].every(
      u => containsInOrder(hermiteOpen(trace, 0.5, 0.1, 200, null, dens(u)),
                           trace)))
  check('density: never falls below the control points',
    counts[counts.length - 1] >= trace.length)
  // v27 guaranteed "never more vertices than the legacy path at any
  // scale". v30 deliberately supersedes that: where the legacy path
  // faceted visibly, refinement now buys smoothness with nodes. The
  // guarantee that survives is the one that matters for drawing speed —
  // at and beyond the scale the geometry was drawn for, it is cheaper.
  const legacy = hermiteOpen(trace, 0.5, 0.1, 200).length
  check('density: cheaper than the legacy path at mapping scale and out',
    [2, 8].every(
      u => hermiteOpen(trace, 0.5, 0.1, 200, null, dens(u)).length <= legacy),
    'legacy ' + legacy)
}

// Cache identity: the same density replays, a different octave rebuilds,
// and no-density is its own key.
check('cache key: same density, same key; different octave, different key',
  densityKey(dens(0.5)) === densityKey(dens(0.5)) &&
  densityKey(dens(0.5)) !== densityKey(dens(1)) &&
  densityKey(null) === '' && densityKey(dens(0)) === '')
{
  const c = {}
  const first = hermiteOpen(wiggle, 0.5, 0.1, 200, c, dens(0.5))
  check('cache: a density hit is bit-identical to the uncached call',
    sameJson(hermiteOpen(wiggle, 0.5, 0.1, 200, c, dens(0.5)),
             hermiteOpen(wiggle, 0.5, 0.1, 200, null, dens(0.5))) &&
    sameJson(first, hermiteOpen(wiggle, 0.5, 0.1, 200, null, dens(0.5))))
  const other = hermiteOpen(wiggle, 0.5, 0.1, 200, c, dens(4))
  check('cache: an octave change invalidates and stays correct',
    sameJson(other, hermiteOpen(wiggle, 0.5, 0.1, 200, null, dens(4))) &&
    c.p[3] === densityKey(dens(4)))
}

// The v26 polygon-confirm win must survive the density change: the idle
// ring and the confirm ring have to be computed at the SAME density, or
// the prefix diff silently degrades to a full O(N^2) rewrite.
{
  const cacheD = {}
  const d = dens(0.5)
  const idleD = ringIdle(square, crossPt, 0.5, 0.1, 200, cacheD, d)
  const confD = confirmSequence(square, true, 0.5, 0.1, 200, cacheD, d)
  const prefixD = Math.min(commonPrefix(idleD, confD), idleD.length - 1,
                           confD.length - 1)
  const popsD = idleD.length - (prefixD + 1)
  check('ring idle at density: confirm write is still 1 pop + 1 add',
    popsD === 1 && confD.length - prefixD === 1,
    'pops ' + popsD + ' adds ' + (confD.length - prefixD))
}

// --- v30 kink refinement ---------------------------------------------
// splineSimplify must still behave exactly as it did once it is built on
// the index pass.
check('simplify: wrapper still returns the same points as before',
  sameJson(simplify(wiggle, 0), wiggle) &&
  simplifyIndices(wiggle, 0).length === wiggle.length &&
  sameJson(simplify([pt(0, 0), pt(1, 0.0001), pt(2, 0)], 0.01),
           [pt(0, 0), pt(2, 0)]))

// Refinement only ever ADDS, never drops or reorders, and is stable.
{
  const line = []
  for (let i = 0; i <= 64; i++)
    line.push(pt(i, 10 * Math.sin(i / 64 * Math.PI)))
  const kept = simplifyIndices(line, 0.5)
  const refined = refineAngles(line, kept, 0.2)
  let sorted = true
  for (let i = 1; i < refined.length; i++)
    if (refined[i] <= refined[i - 1]) sorted = false
  check('refine: returns strictly ascending indices', sorted)
  check('refine: at least as many nodes as the prune kept',
    refined.length >= kept.length)
  check('refine: is idempotent',
    sameJson(refineAngles(line, refined, 0.2), refined))
  check('refine: a maxKink of 0 disables it (the legacy path)',
    refineAngles(line, kept, 0) === kept)
  check('refine: never exceeds the block it draws from',
    refined[refined.length - 1] <= line.length - 1)
}

// A straight run must gain NOTHING — nodes go back only where the line
// actually bends, which is what keeps straight boundaries cheap.
{
  const straight = []
  for (let i = 0; i <= 40; i++)
    straight.push(pt(i * 3, 0))
  check('refine: a straight run gains no nodes',
    sameJson(refineAngles(straight, simplifyIndices(straight, 0.5), 0.2),
             simplifyIndices(straight, 0.5)))
  const dseq = hermiteOpen([pt(0, 0), pt(100, 0), pt(200, 0), pt(300, 0)],
                           0.5, 0.1, 200, null, dens(1))
  check('refine: a straight spline stays minimal', dseq.length <= 8,
    'nodes ' + dseq.length)
}

// The headline guarantee: the faceting the user reported is gone. A lobed
// cover boundary drawn zoomed out used to corner by a full millimetre on
// the map while every vertex sat legitimately within tolerance.
{
  const lobed = []
  for (let i = 0; i < 24; i++) {
    const a = (i / 24) * 2 * Math.PI
    const r = 300 + 60 * Math.sin(5 * a)
    lobed.push(pt(r * Math.cos(a), r * Math.sin(a)))
  }
  for (const u of [0.5, 1, 2, 4]) {
    const seq = hermiteClosed(lobed, 0.5, 0.1, 200, null, dens(u)).points
    const kink = maxKinkPoints(seq, u)
    // The refinement bounds kinks INSIDE each segment block; the junction
    // at a control point is shared between two independently-pruned
    // blocks, so allow a margin there. The curve is C1 at controls, so
    // the residual is of the same order, not a different one.
    check('kink: bounded at ' + u + ' units/point',
      kink <= KINK_RATIO * effTolFor(u) / u * 2.5 + 1e-9,
      kink.toFixed(3) + ' pt (' + (kink * 0.3528).toFixed(3) + ' mm)')
    check('kink: invisible in millimetres at ' + u + ' units/point',
      kink * 0.3528 < 0.14,
      (kink * 0.3528).toFixed(3) + ' mm vs 0.28 mm thinnest stroke')
  }
  // ...and the refinement is what is doing it.
  const off = hermiteClosed(lobed, 0.5, 0.1, 200, null,
    { unitsPerPoint: 4, tolPoints: TOL_POINTS, spacingPoints: SPACING_POINTS,
      minSamples: MIN_SAMPLES, maxKinkRatio: 0 }).points
  const on = hermiteClosed(lobed, 0.5, 0.1, 200, null, dens(4)).points
  check('kink: without refinement the same curve facets far worse',
    maxKinkPoints(off, 4) > 2.5 * maxKinkPoints(on, 4),
    'off ' + maxKinkPoints(off, 4).toFixed(2) + ' pt vs on ' +
    maxKinkPoints(on, 4).toFixed(2) + ' pt')
  // At the scale it was drawn for, still cheaper than the fixed algorithm.
  check('kink: still fewer nodes than the legacy path at map scale',
    hermiteClosed(lobed, 0.5, 0.1, 200, null, dens(2)).points.length <
    hermiteClosed(lobed, 0.5, 0.1, 200).points.length,
    hermiteClosed(lobed, 0.5, 0.1, 200, null, dens(2)).points.length +
    ' vs legacy ' + hermiteClosed(lobed, 0.5, 0.1, 200).points.length)
}

// v26's polygon-confirm win must survive the refinement.
{
  const cacheR = {}
  const d = dens(1)
  const idleR = ringIdle(square, crossPt, 0.5, 0.1, 200, cacheR, d)
  const confR = confirmSequence(square, true, 0.5, 0.1, 200, cacheR, d)
  const pR = Math.min(commonPrefix(idleR, confR), idleR.length - 1,
                      confR.length - 1)
  check('ring idle with refinement: confirm write is still 1 pop + 1 add',
    idleR.length - (pR + 1) === 1 && confR.length - pR === 1,
    'pops ' + (idleR.length - (pR + 1)) + ' adds ' + (confR.length - pR))
}

// --- numeric parity fixtures (generated from the desktop algorithm) --
if (fixturePath) {
  const fixture = JSON.parse(fs.readFileSync(fixturePath, 'utf8'))
  for (const c of fixture.cases) {
    const points = c.points.map(p => pt(p[0], p[1]))
    const got = c.closed
      ? hermiteClosed(points, c.tightness, c.tolerance, c.maxSegments).points
      : hermiteOpen(points, c.tightness, c.tolerance, c.maxSegments)
    let ok = got.length === c.expected.length
    let detail = 'length ' + got.length + ' vs ' + c.expected.length
    if (ok) {
      for (let i = 0; i < got.length; i++) {
        const dx = Math.abs(got[i].x - c.expected[i][0])
        const dy = Math.abs(got[i].y - c.expected[i][1])
        if (dx > 1e-9 || dy > 1e-9) {
          ok = false
          detail = 'point ' + i + ': (' + got[i].x + ', ' + got[i].y +
                   ') vs (' + c.expected[i][0] + ', ' + c.expected[i][1] + ')'
          break
        }
      }
    }
    check('parity: ' + c.name, ok, detail)
  }
}

process.exit(failures === 0 ? 0 : 1)
