// Harness: extract the pure-JS spline math from lgs_companion.qml
// verbatim and check its structural guarantees. With an optional second
// argument, also run numeric parity fixtures generated by
// tests/test_qfield_spline_js.py from the desktop Hermite algorithm.
// Run: node spline_harness.js <path-to-qml> [fixture.json]
'use strict'
const fs = require('fs')

const qmlPath = process.argv[2]
const fixturePath = process.argv[3]
const qml = fs.readFileSync(qmlPath, 'utf8')

function extractFunction(name) {
  const start = qml.indexOf('function ' + name + '(')
  if (start === -1) throw new Error('function not found: ' + name)
  let depth = 0, i = qml.indexOf('{', start)
  const bodyStart = i
  for (; i < qml.length; i++) {
    if (qml[i] === '{') depth++
    else if (qml[i] === '}') { depth--; if (depth === 0) break }
  }
  return 'function ' + name + qml.slice(qml.indexOf('(', start), bodyStart) +
         qml.slice(bodyStart, i + 1)
}

const code = ['splinePointScalar', 'splinePointsAdd', 'splineTangent',
  'splinePerpDist', 'splineSimplify', 'splineDecimate', 'splineSamePoint',
  'splineCacheEntries', 'splineCacheLookup', 'splineHermiteOpen',
  'splineHermiteClosed', 'splineBuildSequence', 'splineConfirmSequence',
  'splineCommonPrefixLength']
  .map(extractFunction).join('\n');
// Indirect eval: runs non-strict in global scope so the extracted
// function declarations become globals.
(0, eval)(code)
const simplify = globalThis.splineSimplify
const hermiteOpen = globalThis.splineHermiteOpen
const hermiteClosed = globalThis.splineHermiteClosed
const buildSequence = globalThis.splineBuildSequence
const confirmSequence = globalThis.splineConfirmSequence
const commonPrefix = globalThis.splineCommonPrefixLength
const decimate = globalThis.splineDecimate

let failures = 0
function check(label, ok, detail) {
  if (ok) { console.log('PASS ' + label) }
  else { failures++; console.log('FAIL ' + label + (detail ? '\n  ' + detail : '')) }
}

function pt(x, y, z) { return { x: x, y: y, z: z } }
function samePt(a, b) { return a.x === b.x && a.y === b.y }
function containsInOrder(seq, controls) {
  let at = 0
  for (const c of controls) {
    while (at < seq.length && !samePt(seq[at], c)) at++
    if (at === seq.length) return false
    at++
  }
  return true
}

// --- passthrough below 3 points -----------------------------------
const two = [pt(0, 0), pt(1, 1)]
check('open passthrough < 3 points',
  JSON.stringify(hermiteOpen(two, 0.5, 0, 8)) === JSON.stringify(two))
check('closed passthrough < 3 points',
  JSON.stringify(hermiteClosed(two, 0.5, 0, 8).points) === JSON.stringify(two))
check('buildSequence passthrough < 3 distinct points',
  JSON.stringify(buildSequence([pt(0, 0), pt(1, 1), pt(1, 1)], false, 0.5, 0, 8))
    === JSON.stringify([pt(0, 0), pt(1, 1)]))

// --- open curve: exact endpoints, controls preserved in order -------
const wiggle = [pt(0, 0, 100), pt(10, 5, 110), pt(20, -5, 120), pt(30, 0, 130)]
const open8 = hermiteOpen(wiggle, 0.5, 0, 8)
check('open endpoints exact',
  samePt(open8[0], wiggle[0]) && samePt(open8[open8.length - 1], wiggle[3]))
check('open controls preserved in order', containsInOrder(open8, wiggle))
// tolerance=0 keeps every sample: n controls + (n-1) * (maxSegments-1)
check('open exact count at tolerance 0 (maxSegments 8)',
  open8.length === 4 + 3 * 7, 'got ' + open8.length)

// --- collinear input prunes back to the control points --------------
const line = [pt(0, 0), pt(1, 0), pt(2, 0), pt(3, 0)]
const pruned = hermiteOpen(line, 0.5, 0.5, 8)
check('collinear prunes to controls',
  pruned.length === 4 && line.every((c, i) => samePt(pruned[i], c)),
  'got ' + JSON.stringify(pruned))

// --- z handling -----------------------------------------------------
const zLinear = open8.every((p, i) => {
  if (i === 0) return p.z === 100
  return p.z >= open8[i - 1].z - 1e-9
})
check('z present, exact at controls, non-decreasing', zLinear &&
  open8[open8.length - 1].z === 130)
const open2d = hermiteOpen([pt(0, 0), pt(10, 5), pt(20, -5)], 0.5, 0, 8)
check('2D input yields NaN sample z, xy stays finite',
  open2d.every(p => isFinite(p.x) && isFinite(p.y)) &&
  open2d.some(p => Number.isNaN(p.z)))

// --- closed ring ----------------------------------------------------
const square = [pt(0, 0), pt(10, 0), pt(10, 10), pt(0, 10)]
const ring = hermiteClosed(square, 0.5, 0, 8)
check('closed: all controls present', containsInOrder(ring.points, square))
check('closed: no closing duplicate',
  !samePt(ring.points[0], ring.points[ring.points.length - 1]))
check('closed: lastControlIndex points at last control',
  samePt(ring.points[ring.lastControlIndex], square[3]))
check('closed: wrap samples follow the last control',
  ring.points.length > ring.lastControlIndex + 1)
// n segments * (maxSegments-1) samples + n controls
check('closed exact count at tolerance 0 (maxSegments 8)',
  ring.points.length === 4 + 4 * 7, 'got ' + ring.points.length)

// --- buildSequence rotation (closed) --------------------------------
const seq = buildSequence(square, true, 0.5, 0, 8)
check('rotation: crosshair control is last', samePt(seq[seq.length - 1], square[3]))
check('rotation: length preserved', seq.length === ring.points.length)
check('rotation: first element is a wrap sample',
  samePt(seq[0], ring.points[ring.lastControlIndex + 1]))
check('rotation: all controls present', containsInOrder(
  seq.slice(seq.indexOf(seq.find(p => samePt(p, square[0])))), square))

// --- buildSequence open ends at crosshair ---------------------------
const seqOpen = buildSequence(wiggle, false, 0.5, 0, 8)
check('open sequence ends at crosshair',
  samePt(seqOpen[seqOpen.length - 1], wiggle[3]))

// --- confirmSequence: committed controls only, no crosshair ---------
check('confirm open: null below 2 distinct controls',
  confirmSequence([pt(0, 0), pt(0, 0)], false, 0.5, 0, 8) === null &&
  confirmSequence([], false, 0.5, 0, 8) === null)
check('confirm closed: null below 3 distinct controls',
  confirmSequence([pt(0, 0), pt(10, 0)], true, 0.5, 0, 8) === null)
check('confirm open: 2 controls pass through as the plain segment',
  JSON.stringify(confirmSequence(two, false, 0.5, 0, 8)) ===
  JSON.stringify(two))
const confOpen = confirmSequence(wiggle, false, 0.5, 0, 8)
check('confirm open: endpoints are the first/last CONTROLS',
  samePt(confOpen[0], wiggle[0]) &&
  samePt(confOpen[confOpen.length - 1], wiggle[3]))
check('confirm open: all controls present in order',
  containsInOrder(confOpen, wiggle))
check('confirm open matches the committed-only curve',
  JSON.stringify(confOpen) === JSON.stringify(hermiteOpen(wiggle, 0.5, 0, 8)))
const confRing = confirmSequence(square, true, 0.5, 0, 8)
check('confirm closed: all controls present, no closing duplicate',
  containsInOrder(confRing, square) &&
  !samePt(confRing[0], confRing[confRing.length - 1]))
check('confirm closed matches the committed-only ring',
  JSON.stringify(confRing) ===
  JSON.stringify(hermiteClosed(square, 0.5, 0, 8).points))
// The property the confirm fixup exists for: the sequence the crosshair
// WOULD have contributed (buildSequence with the crosshair appended)
// differs past the last control — confirm uses the controls-only curve.
const jiggled = pt(99, 99)
const withCross = buildSequence(wiggle.concat([jiggled]), false, 0.5, 0, 8)
check('confirm: crosshair never contributes',
  !confOpen.some(p => samePt(p, jiggled)) &&
  samePt(withCross[withCross.length - 1], jiggled) &&
  !samePt(confOpen[confOpen.length - 1], jiggled))

// --- duplicates never explode ---------------------------------------
const dup = buildSequence(
  [pt(0, 0), pt(0, 0), pt(10, 5), pt(10, 5), pt(20, 0)], false, 0.5, 0, 8)
check('duplicate controls produce finite xy',
  dup.every(p => isFinite(p.x) && isFinite(p.y)))

// --- decimate (freehand node thinning) -------------------------------
const dense = []
for (let i = 0; i <= 20; i++) dense.push(pt(i, 0, i))
check('decimate: minDist 0 is identity',
  JSON.stringify(decimate(dense, 0)) === JSON.stringify(dense))
const thinned = decimate(dense, 5)
check('decimate: keeps first and last',
  samePt(thinned[0], dense[0]) &&
  samePt(thinned[thinned.length - 1], dense[20]))
check('decimate: dense run collapses to every 5th point',
  thinned.length === 5 &&
  thinned.every((p, i) => i === thinned.length - 1 || p.x === i * 5),
  'got ' + JSON.stringify(thinned))
check('decimate: kept points carry their z',
  thinned.every(p => p.z === p.x))
const sparse = [pt(0, 0), pt(10, 0), pt(20, 0)]
check('decimate: already-sparse input passes through',
  JSON.stringify(decimate(sparse, 5)) === JSON.stringify(sparse))
check('decimate: two points always survive',
  decimate([pt(0, 0), pt(1, 0)], 100).length === 2)

// --- simplify basics ------------------------------------------------
const spike = [pt(0, 0), pt(1, 0.001), pt(2, 5), pt(3, 0.001), pt(4, 0)]
check('simplify: tolerance 0 is identity',
  JSON.stringify(simplify(spike, 0)) === JSON.stringify(spike))
const simp = simplify(spike, 0.01)
check('simplify: keeps endpoints and the spike',
  samePt(simp[0], spike[0]) && samePt(simp[simp.length - 1], spike[4]) &&
  simp.some(p => samePt(p, spike[2])))
const nearFlat = [pt(0, 0), pt(1, 0.001), pt(2, 0.002), pt(4, 0)]
check('simplify: drops sub-tolerance points',
  simplify(nearFlat, 0.01).length === 2,
  'got ' + JSON.stringify(simplify(nearFlat, 0.01)))

// --- common prefix (incremental rebuild diff) -----------------------
const seqA = [pt(0, 0, 1), pt(1, 1, 2), pt(2, 2, 3)]
check('prefix: identical arrays -> full length',
  commonPrefix(seqA, seqA.map(p => pt(p.x, p.y, p.z))) === 3)
check('prefix: divergence mid-array',
  commonPrefix(seqA, [pt(0, 0, 1), pt(1, 1.5, 2), pt(2, 2, 3)]) === 1)
check('prefix: shorter second array caps the walk',
  commonPrefix(seqA, [pt(0, 0, 1)]) === 1)
check('prefix: empty arrays', commonPrefix([], seqA) === 0)
check('prefix: z mismatch counts as divergence',
  commonPrefix(seqA, [pt(0, 0, 1), pt(1, 1, 9), pt(2, 2, 3)]) === 1)
check('prefix: NaN z equals NaN z',
  commonPrefix([pt(0, 0, NaN), pt(1, 1, NaN)],
               [pt(0, 0, NaN), pt(1, 1, NaN)]) === 2)
check('prefix: undefined z equals NaN z',
  commonPrefix([pt(0, 0), pt(1, 1)],
               [pt(0, 0, NaN), pt(1, 1, NaN)]) === 2)
// The property the incremental rebuild relies on: moving only the
// crosshair leaves a long stable prefix on an open curve.
const cross1 = hermiteOpen(wiggle.slice(0, 3).concat([pt(31, 1, 130)]), 0.5, 0, 8)
const cross2 = hermiteOpen(wiggle.slice(0, 3).concat([pt(33, -2, 130)]), 0.5, 0, 8)
check('prefix: crosshair move keeps stable prefix on open curve',
  commonPrefix(cross1, cross2) >= 1 + 7 + 1,  // first segment + controls
  'got ' + commonPrefix(cross1, cross2))

// --- segment cache: cached output is bit-identical -------------------
// The confirm-path cache must never change the produced curve — only
// skip recomputing segments whose dependencies are unchanged.
function sameJson(a, b) { return JSON.stringify(a) === JSON.stringify(b) }
const cacheO = {}
const grow = [pt(0, 0, 100), pt(10, 5, 110), pt(20, -5, 120)]
let growOk = true
for (const next of [pt(30, 0, 130), pt(40, 8, 140), pt(45, 20, 150)]) {
  grow.push(next)
  if (!sameJson(hermiteOpen(grow, 0.5, 0.1, 200, cacheO),
                hermiteOpen(grow, 0.5, 0.1, 200)))
    growOk = false
}
check('cache open: incremental appends stay bit-identical', growOk)
grow.pop()
check('cache open: pop stays bit-identical',
  sameJson(hermiteOpen(grow, 0.5, 0.1, 200, cacheO),
           hermiteOpen(grow, 0.5, 0.1, 200)))
const cacheC = {}
const ringGrow = [pt(0, 0), pt(10, 0), pt(10, 10)]
let ringOk = true
for (const next of [pt(5, 15), pt(0, 10)]) {
  ringGrow.push(next)
  const cached = hermiteClosed(ringGrow, 0.5, 0.1, 200, cacheC)
  const plain = hermiteClosed(ringGrow, 0.5, 0.1, 200)
  if (!sameJson(cached.points, plain.points) ||
      cached.lastControlIndex !== plain.lastControlIndex)
    ringOk = false
}
check('cache closed: incremental appends stay bit-identical', ringOk)
check('cache: buildSequence with cache matches without (closed rotation)',
  sameJson(buildSequence(ringGrow, true, 0.5, 0.1, 200, cacheC),
           buildSequence(ringGrow, true, 0.5, 0.1, 200)))
check('cache: confirmSequence with cache matches without',
  sameJson(confirmSequence(wiggle, false, 0.5, 0, 8, {}),
           confirmSequence(wiggle, false, 0.5, 0, 8)))
// The property the cache exists for: a repeated call replays the exact
// stored blocks (object identity, not just equal values)...
const cacheHit = {}
const hit1 = hermiteOpen(wiggle, 0.5, 0, 8, cacheHit)
const hit2 = hermiteOpen(wiggle, 0.5, 0, 8, cacheHit)
check('cache: repeated call reuses stored blocks (object identity)',
  hit2.length === hit1.length && hit2[1] === hit1[1])
// ...and a moved last point (the crosshair) leaves the early segments'
// blocks untouched while the tail recomputes.
const cacheTail = {}
const tail1 = hermiteOpen(wiggle.concat([pt(40, 0, 140)]), 0.5, 0, 8, cacheTail)
const tail2 = hermiteOpen(wiggle.concat([pt(41, 3, 140)]), 0.5, 0, 8, cacheTail)
check('cache: crosshair move keeps early blocks (identity), tail differs',
  tail2[1] === tail1[1] &&
  !samePt(tail2[tail2.length - 2], tail1[tail1.length - 2]))
// Open and closed entries never cross-contaminate, even for the same
// control points.
const cacheKind = {}
hermiteClosed(square, 0.5, 0, 8, cacheKind)
check('cache: open/closed kinds are separate',
  sameJson(hermiteOpen(square, 0.5, 0, 8, cacheKind),
           hermiteOpen(square, 0.5, 0, 8)))
// A parameter change invalidates everything.
const cacheParams = {}
hermiteOpen(wiggle, 0.5, 0, 8, cacheParams)
check('cache: params change invalidates and stays correct',
  sameJson(hermiteOpen(wiggle, 0.8, 0, 8, cacheParams),
           hermiteOpen(wiggle, 0.8, 0, 8)) &&
  cacheParams.p[0] === 0.8)

// --- numeric parity fixtures (generated from the desktop algorithm) --
if (fixturePath) {
  const fixture = JSON.parse(fs.readFileSync(fixturePath, 'utf8'))
  for (const c of fixture.cases) {
    const points = c.points.map(p => pt(p[0], p[1]))
    const got = c.closed
      ? hermiteClosed(points, c.tightness, c.tolerance, c.maxSegments).points
      : hermiteOpen(points, c.tightness, c.tolerance, c.maxSegments)
    let ok = got.length === c.expected.length
    let detail = 'length ' + got.length + ' vs ' + c.expected.length
    if (ok) {
      for (let i = 0; i < got.length; i++) {
        const dx = Math.abs(got[i].x - c.expected[i][0])
        const dy = Math.abs(got[i].y - c.expected[i][1])
        if (dx > 1e-9 || dy > 1e-9) {
          ok = false
          detail = 'point ' + i + ': (' + got[i].x + ', ' + got[i].y +
                   ') vs (' + c.expected[i][0] + ', ' + c.expected[i][1] + ')'
          break
        }
      }
    }
    check('parity: ' + c.name, ok, detail)
  }
}

process.exit(failures === 0 ? 0 : 1)
