// Harness: extract the level-clustering mirror (clusterLevels & helpers)
// from lgs_companion.qml verbatim — INCLUDING the readonly constant
// properties they read, so the QML values themselves are under test,
// never hand-copied here — and run numeric parity fixtures generated by
// tests/test_qfield_zlevels_js.py from z_filter/levels.py.
// Run: node z_levels_harness.js <path-to-qml> [fixture.json]
'use strict'
const fs = require('fs')

const qmlPath = process.argv[2]
const fixturePath = process.argv[3]
const qml = fs.readFileSync(qmlPath, 'utf8')

function extractFunction(name) {
  const start = qml.indexOf('function ' + name + '(')
  if (start === -1) throw new Error('function not found: ' + name)
  let depth = 0, i = qml.indexOf('{', start)
  const bodyStart = i
  for (; i < qml.length; i++) {
    if (qml[i] === '{') depth++
    else if (qml[i] === '}') { depth--; if (depth === 0) break }
  }
  return 'function ' + name + qml.slice(qml.indexOf('(', start), bodyStart) +
         qml.slice(bodyStart, i + 1)
}

// The mirror functions reference the plugin's constants unqualified
// (gapFloor, minTol, ...); turn every numeric readonly property into a
// global before evaluating them.
let constants = ''
for (const m of qml.matchAll(
    /readonly property (?:real|int) (\w+): ([0-9eE+.-]+)/g))
  constants += 'var ' + m[1] + ' = ' + m[2] + '\n'

const code = constants + ['labelElevation', 'rangeVote', 'medianOf',
  'niceStep', 'niceStepNearest', 'binContinuous', 'summarizeCluster',
  'clusterLevels', 'suggestTolerance', 'topSuggestions', 'suggestStep',
  'attachLabels', 'parseBakedSuggestions']
  .map(extractFunction).join('\n');
// Indirect eval: runs non-strict in global scope so the extracted
// declarations become globals.
(0, eval)(code)

let failures = 0
function check(label, ok, detail) {
  if (ok) { console.log('PASS ' + label) }
  else { failures++; console.log('FAIL ' + label + (detail ? '\n  ' + detail : '')) }
}

check('constants extracted from the QML',
  [globalThis.gapFloor, globalThis.gapFactor, globalThis.gapEps,
   globalThis.minTol, globalThis.tolMargin, globalThis.maxTol,
   globalThis.maxSuggestions, globalThis.defaultStep, globalThis.stepFloor,
   globalThis.flatSpan, globalThis.levelSpanCap, globalThis.labelSlack]
    .every(v => typeof v === 'number' && !Number.isNaN(v)))

if (fixturePath) {
  const fixture = JSON.parse(fs.readFileSync(fixturePath, 'utf8'))
  const near = (a, b) => Math.abs(a - b) <= 1e-9

  // Vote parity: which elevation a feature contributes, python-None ↔
  // JS-undefined for the abstentions.
  for (const v of fixture.votes || []) {
    const got = globalThis.rangeVote(v.z_min, v.z_max,
        v.label === null ? undefined : v.label)
    const ok = v.want === null ? got === undefined
        : (got !== undefined && near(got, v.want))
    check('vote: ' + v.name, ok, got + ' vs ' + v.want)
  }

  for (const c of fixture.cases) {
    const clusters = globalThis.attachLabels(
        globalThis.clusterLevels(c.counts), c.value_labels || {})
    let ok = clusters.length === c.clusters.length
    let detail = 'length ' + clusters.length + ' vs ' + c.clusters.length
    if (ok) {
      for (let i = 0; i < clusters.length; i++) {
        const want = c.clusters[i]
        // Python omits 'label' when none, arriving here as undefined.
        const labelOk = (want.label === undefined) ===
            (clusters[i].label === undefined) &&
            (want.label === undefined || want.label === clusters[i].label)
        if (!near(clusters[i].level, want.level) ||
            clusters[i].count !== want.count ||
            !near(clusters[i].lo, want.lo) ||
            !near(clusters[i].hi, want.hi) ||
            !near(clusters[i].suggested_tol, want.suggested_tol) ||
            !labelOk) {
          ok = false
          detail = 'cluster ' + i + ': ' + JSON.stringify(clusters[i]) +
                   ' vs ' + JSON.stringify(want)
          break
        }
      }
    }
    check('clusters: ' + c.name, ok, detail)
    const auto = globalThis.suggestTolerance(clusters)
    check('auto tol: ' + c.name, near(auto, c.auto),
          auto + ' vs ' + c.auto)
    const step = globalThis.suggestStep(clusters)
    check('step: ' + c.name, near(step, c.step), step + ' vs ' + c.step)
  }

  // Baked-suggestion payload parity: python format_suggestions output must
  // parse identically on the device (python-None ↔ JS-undefined for the
  // optional fields).
  const nullish = v => v === null || v === undefined
  for (const b of fixture.baked || []) {
    const got = globalThis.parseBakedSuggestions(b.payload)
    if (b.want === null) {
      check('baked null: ' + b.name, got === null, JSON.stringify(got))
      continue
    }
    let ok = got !== null && got.suggestions.length === b.want.suggestions.length
    let detail = got === null ? 'parsed to null'
        : 'length ' + got.suggestions.length + ' vs ' +
          b.want.suggestions.length
    if (ok) {
      for (let i = 0; i < got.suggestions.length; i++) {
        const g = got.suggestions[i], w = b.want.suggestions[i]
        const labelOk = (w.label === undefined) === (g.label === undefined) &&
            (w.label === undefined || w.label === g.label)
        if (!near(g.level, w.level) || g.count !== w.count ||
            !near(g.lo, w.lo) || !near(g.hi, w.hi) ||
            !near(g.suggested_tol, w.suggested_tol) || !labelOk) {
          ok = false
          detail = 'entry ' + i + ': ' + JSON.stringify(g) + ' vs ' +
                   JSON.stringify(w)
          break
        }
      }
      const wi = b.want, gi = got.info
      const optOk = (a, b2) => (nullish(a) && nullish(b2)) ||
          (!nullish(a) && !nullish(b2) && near(a, b2))
      if (ok && !(optOk(gi.min, wi.min) && optOk(gi.max, wi.max) &&
                  gi.withElev === wi.with_elev && gi.blank === wi.blank &&
                  gi.spanning === wi.spanning)) {
        ok = false
        detail = 'info ' + JSON.stringify(gi) + ' vs ' + JSON.stringify(wi)
      }
    }
    check('baked: ' + b.name, ok, detail)
  }
}

process.exit(failures === 0 ? 0 : 1)
